Document: prueba
Title: Debian prueba Manual
Author: <insert document author here>
Abstract: This manual describes what prueba is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prueba/prueba.sgml.gz

Format: postscript
Files: /usr/share/doc/prueba/prueba.ps.gz

Format: text
Files: /usr/share/doc/prueba/prueba.text.gz

Format: HTML
Index: /usr/share/doc/prueba/html/index.html
Files: /usr/share/doc/prueba/html/*.html
